// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ztnnmgnoschgreqsodfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bm5tZ25vc2NoZ3JlcXNvZGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyOTExMjQsImV4cCI6MjA4OTg2NzEyNH0.1c_CxI5sNKrTA0AU_-DLaqpC7eMTYI44dM3sH9B1sDo";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);